# Chapter 10
# Working with Data
### NUMPY

In [1]:
# to install numpy
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
# creating a list
list1 = [2, 4, 5, 7]

# Creating a numpy array from the existing list
arr = np.array(list1)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr[1]

4

In [6]:
arr[2]

5

In [7]:
arr[3]

7

In [8]:
arr[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [13]:
arr[3] = 8

In [14]:
print(arr)

[2 4 5 8]


In [15]:
arr[-1]

8

In [16]:
arr[-2]

5

In [17]:
arr[-3]

4

In [18]:
arr[-4]

2

In [19]:
arr[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(11,31,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [22]:
np.arange(5, 20, 33, dtype=float)

array([5.])

In [23]:
np.zeros(shape=3, dtype=int)

array([0, 0, 0])

In [24]:
np.ones(shape=6)

array([1., 1., 1., 1., 1., 1.])

In [25]:
np.ones(shape=3)

array([1., 1., 1.])

In [26]:
np.zeros(shape=(3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(start=1, stop=5, num=5)

array([1., 2., 3., 4., 5.])

In [30]:
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(N=6, M=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
# to generate a random number
np.random.rand()

0.37363733157138856

In [33]:
# To generate 3 random numbers
np.random.rand(3)

array([0.51808944, 0.87804178, 0.7137482 ])

In [34]:
# To generate random numbers in 3x5 array format
np.random.rand(3,5)

array([[0.46845275, 0.20512755, 0.87316788, 0.8002459 , 0.18601173],
       [0.92412136, 0.46969864, 0.2755424 , 0.99201301, 0.99857492],
       [0.41699626, 0.25039897, 0.03745115, 0.18041594, 0.57253621]])

In [35]:
np.random.randn()

3.1364101335643215

In [36]:
np.random.randn(3, 5)

array([[-0.94674748,  0.57982342,  0.82603621, -1.32294965, -1.06568916],
       [-0.57034977, -1.41563032, -0.26262824, -0.73798919, -0.0082135 ],
       [-1.39675675,  0.6243449 ,  1.27253393,  0.8591462 ,  0.06165553]])

In [37]:
# Generate a random integer between 1 & 10
np.random.randint(10)

2

In [38]:
# Generate a random integer between 20 and 40
np.random.randint(20, 40)

26

In [39]:
# Generate 5 random integers between 20 and 40
np.random.randint(20, 40, 5)

array([34, 37, 20, 26, 38])

In [40]:
print(arr)

[2 4 5 8]


In [41]:
# Generate a random number from an array
np.random.choice(arr)

4

In [42]:
# Generate a random number from a list
np.random.choice([1, 2, 3, 4])

4

In [43]:
# Generate 2x4 matrix of random values from a list
np.random.choice([1, 2, 3, 4], size=(2, 4))

array([[1, 1, 4, 3],
       [1, 1, 2, 1]])

### PANDAS

In [10]:
# To Install Pandas
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import pandas as pd

In [44]:
data = pd.Series([2,4,6,8,10,12,14,16])
data

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64

In [45]:
type(data)

pandas.core.series.Series

In [46]:
data.values

array([ 2,  4,  6,  8, 10, 12, 14, 16], dtype=int64)

In [47]:
data.index

RangeIndex(start=0, stop=8, step=1)

In [48]:
print(arr)

[2 4 5 8]


In [51]:
print(type(arr))

<class 'numpy.ndarray'>


In [52]:
ser = pd.Series(arr)
print(type(ser))
print(ser)

<class 'pandas.core.series.Series'>
0    2
1    4
2    5
3    8
dtype: int32


In [53]:
data1 = pd.Series( [1,2,3,4,5,6,7,8], index = ['a','b','c','d','e','f','g','h'] )
print(data1)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64


In [54]:
data1['c']

3

In [55]:
data1[2]

C:\Users\Pc\AppData\Local\Temp\ipykernel_12600\3899140294.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data1[2]


3

In [56]:
movies_dict = {'The Kashmir Files':20.00, 'Kantara':7.50, 'KGF Chapter 2':90.00, 'RRR':130.00}
print(type(movies_dict))
print(movies_dict)

<class 'dict'>
{'The Kashmir Files': 20.0, 'Kantara': 7.5, 'KGF Chapter 2': 90.0, 'RRR': 130.0}


In [57]:
movies = pd.Series(movies_dict)
print(type(movies))
print(movies)

<class 'pandas.core.series.Series'>
The Kashmir Files     20.0
Kantara                7.5
KGF Chapter 2         90.0
RRR                  130.0
dtype: float64


In [58]:
movies['Kantara']

7.5

In [59]:
movies['Kantara':'RRR']

Kantara            7.5
KGF Chapter 2     90.0
RRR              130.0
dtype: float64

In [60]:
movies_profit = {'The Kashmir Files':252.00, 'Kantara':81.10, 'KGF Chapter 2':434.62, 'RRR':277.00}
print(type(movies))
print(movies)

<class 'pandas.core.series.Series'>
The Kashmir Files     20.0
Kantara                7.5
KGF Chapter 2         90.0
RRR                  130.0
dtype: float64


In [61]:
profit = pd.Series(movies_profit)
print(type(profit))
print(profit)

<class 'pandas.core.series.Series'>
The Kashmir Files    252.00
Kantara               81.10
KGF Chapter 2        434.62
RRR                  277.00
dtype: float64


### Pandas DataFrame

In [62]:
movies_db = pd.DataFrame({'Budget':movies, 'Profit':profit})
print(movies_db)

                   Budget  Profit
The Kashmir Files    20.0  252.00
Kantara               7.5   81.10
KGF Chapter 2        90.0  434.62
RRR                 130.0  277.00


In [63]:
movies_db.columns

Index(['Budget', 'Profit'], dtype='object')

In [64]:
movies_db.index

Index(['The Kashmir Files', 'Kantara', 'KGF Chapter 2', 'RRR'], dtype='object')

In [65]:
movies_db.count()

Budget    4
Profit    4
dtype: int64

In [66]:
movies_db.sum()

Budget     247.50
Profit    1044.72
dtype: float64

In [67]:
movies_db.mean()

Budget     61.875
Profit    261.180
dtype: float64

In [68]:
movies_db.median()

Budget     55.0
Profit    264.5
dtype: float64

In [69]:
movies_db.std()

Budget     58.144038
Profit    144.735143
dtype: float64

In [70]:
movies_db.min()

Budget     7.5
Profit    81.1
dtype: float64

In [71]:
movies_db.max()

Budget    130.00
Profit    434.62
dtype: float64

In [72]:
movies_db.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, The Kashmir Files to RRR
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Budget  4 non-null      float64
 1   Profit  4 non-null      float64
dtypes: float64(2)
memory usage: 268.0+ bytes


In [73]:
movies_db.describe()

Budget      Profit
count    4.000000    4.000000
mean    61.875000  261.180000
std     58.144038  144.735143
min      7.500000   81.100000
25%     16.875000  209.275000
50%     55.000000  264.500000
75%    100.000000  316.405000
max    130.000000  434.620000

In [74]:
movies_db.to_csv('movies.csv')

In [75]:
import os
os.getcwd()

'C:\\Users\\Pc\\Documents\\Chandrika\\Chapters\\CodeFiles'

In [76]:
os.listdir()

['.ipynb_checkpoints',
 'Chapter 10.ipynb',
 'Chapter 12 CS1.ipynb',
 'Chapter 12 CS2.ipynb',
 'Chapter 4.ipynb',
 'Chapter 5.ipynb',
 'Chapter 6.ipynb',
 'Chapter 7.ipynb',
 'Chapter 8.ipynb',
 'Chapter 9.ipynb',
 'Files',
 'module1.py',
 'module2.py',
 'movies.csv',
 'MyTextFile.txt',
 '__pycache__']

In [77]:
df = pd.read_csv('movies.csv')
df

Unnamed: 0  Budget  Profit
0  The Kashmir Files    20.0  252.00
1            Kantara     7.5   81.10
2      KGF Chapter 2    90.0  434.62
3                RRR   130.0  277.00

In [78]:
df.rename(columns={'Unnamed: 0': 'Movie'}, inplace=True)
df

Movie  Budget  Profit
0  The Kashmir Files    20.0  252.00
1            Kantara     7.5   81.10
2      KGF Chapter 2    90.0  434.62
3                RRR   130.0  277.00

### Pandas Indexing

In [79]:
S = pd.Series( ['a','b','c','d','e','f','g','h'], index=[1,2,3,4,5,6,7,8] )
print(type(S))
print(S)

<class 'pandas.core.series.Series'>
1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object


In [80]:
S[1:3]

2    b
3    c
dtype: object

In [81]:
# integral index
S.iloc[1:3]

2    b
3    c
dtype: object

In [82]:
# user defined index
S.loc[1:3]

1    a
2    b
3    c
dtype: object

### Data Preprocessing Techniques

In [83]:
var1 = np.array([1, 3, None, 4])
var1

array([1, 3, None, 4], dtype=object)

In [84]:
var1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [85]:
type(np.nan)

float

In [86]:
var2 = np.array([1, 3, np.nan, 4])
var2

array([ 1.,  3., nan,  4.])

In [87]:
var2.sum()

nan

In [88]:
1 + np.nan

nan

In [89]:
100 * np.nan

nan

In [90]:
var2.max()

nan

In [91]:
var2.min()

nan

In [92]:
np.nansum(var2)

8.0

In [93]:
np.nanmin(var2)

1.0

In [94]:
np.nanmax(var2)

4.0

In [95]:
ser1 = pd.Series([1, np.nan, 4, None])
ser1

0    1.0
1    NaN
2    4.0
3    NaN
dtype: float64

In [96]:
ser1.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [97]:
ser1.isnull().sum()

2

In [98]:
ser1.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [99]:
ser1.notnull().sum()

2

In [100]:
# create a sample DataFrame with missing values
df = pd.DataFrame({'Col 1': [1, 2, None, 4], 'Col 2': [5, None, 7, None]})
print("df:\n", df)

# fill missing values with 0
df.fillna(0, inplace=True)

print("After fillna, df:\n", df)

df:
    Col 1  Col 2
0    1.0    5.0
1    2.0    NaN
2    NaN    7.0
3    4.0    NaN
After fillna, df:
    Col 1  Col 2
0    1.0    5.0
1    2.0    0.0
2    0.0    7.0
3    4.0    0.0


In [101]:
# create a sample DataFrame with missing values
df = pd.DataFrame({'Col 1': [1, 2, None, 4], 'Col 2': [5, None, 7, None]})
print("df:\n", df)

# drop rows with missing values
df.dropna(inplace=True)

print("After dropna, df:\n", df)

df:
    Col 1  Col 2
0    1.0    5.0
1    2.0    NaN
2    NaN    7.0
3    4.0    NaN
After dropna, df:
    Col 1  Col 2
0    1.0    5.0


In [102]:
# create a sample DataFrame with missing values
df = pd.DataFrame({'Col 1': [1, 2, None, 4], 'Col 2': [5, None, 7, None]})
print("df:\n", df)

# fill missing values with linear interpolation
df.interpolate(method='linear', inplace = True)

print("After interpolation, df: \n", df)

df:
    Col 1  Col 2
0    1.0    5.0
1    2.0    NaN
2    NaN    7.0
3    4.0    NaN
After interpolation, df: 
    Col 1  Col 2
0    1.0    5.0
1    2.0    6.0
2    3.0    7.0
3    4.0    7.0
